### ISSUE TITLE
Evaluate: Numbers cannot be recognized if there are signs in front of them (Basic)

### ISSUE THREAD

**Issue by thnhmai06** [maan-patel/advanced-calculator#2]
Numbers cannot be recognized if there are signs in front of them
When calculate with numbers which has signs in front of, it returns an error: **`Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'func')`**

```js
-> const math = require('advanced-calculator');
undefined
-> math.evaluate("1")
1
-> math.evaluate("+1")
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'func')
    at eval (<project>/node_modules/advanced-calculator/src/Basic/shunting.js:260:14)
    at eval (<project>/node_modules/advanced-calculator/src/Basic/shunting.js:264:34)
    at evaluate (<project>/node_modules/advanced-calculator/src/Basic/index.js:11:15)
    at <anonymous> (repl:1:6)
-> math.evaluate("-1")
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'func')
    at eval (<project>/node_modules/advanced-calculator/src/Basic/shunting.js:260:14)
    at eval (<project>/node_modules/advanced-calculator/src/Basic/shunting.js:264:34)
    at evaluate (<project>/node_modules/advanced-calculator/src/Basic/index.js:11:15)
    at <anonymous> (repl:1:6)
-> math.evaluate("-1-1")
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'func')
    at eval (<project>/node_modules/advanced-calculator/src/Basic/shunting.js:260:14)
    at eval (<project>/node_modules/advanced-calculator/src/Basic/shunting.js:264:34)
    at eval (<project>/node_modules/advanced-calculator/src/Basic/shunting.js:264:34)
    at evaluate (<project>/node_modules/advanced-calculator/src/Basic/index.js:11:15)
    at <anonymous> (repl:1:6)
-> math.evaluate("(-1)-1")
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'func')
    at eval (<project>/node_modules/advanced-calculator/src/Basic/shunting.js:260:14)
    at eval (<project>/node_modules/advanced-calculator/src/Basic/shunting.js:264:34)
    at eval (<project>/node_modules/advanced-calculator/src/Basic/shunting.js:264:34)
    at evaluate (<project>/node_modules/advanced-calculator/src/Basic/index.js:11:15)
    at <anonymous> (repl:1:6)
```

**Comment by maan-patel** [comment]
Thanks for reporting this. It has been fixed in the PR below:

https://github.com/maan-patel/advanced-calculator/pull/3
